using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Toasts.UI;

[GenerateTypedNameReferences]
public partial class ToastsUI : BaseWindow
{
    public ToastsUI()
    {
        UserInterfaceManager.WindowRoot.AddChild(this);
        RobustXamlLoader.Load(this);
    }

    public void Test()
    {
        Logger.Info("Inside ToastsUI test.");
    }
}
