using Content.Client.UserInterface.Systems.TattleSystem.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Systems.TattleSystem.Widgets;

/// <summary>
///     The status effects display on the right side of the screen.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TattleSystemBar : UIWidget
{
    public void Test(EntityUid uid)
    {
        Logger.Info("Test inside Tattle.xaml hit!");

        var tattleControl = new TattleControl(uid);

        TattleSystemContainer.Children.Add(tattleControl);
    }
}
