using Content.Client.UserInterface.Systems.TattleSystem.Controls;
using Content.Shared.Tattle;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Systems.TattleSystem.Widgets;

/// <summary>
///     The Tattle buttons that are displayed top-right in the HUD
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TattleSystemBar : UIWidget
{
    public void SyncTattlesUI(TattleComponent tattleComponent)
    {
        TattleSystemContainer.Children.Clear();

        foreach (var Tattle in tattleComponent.Tattles)
        {
            var tattleControl = new TattleControl(Tattle);

            TattleSystemContainer.Children.Add(tattleControl);
        }
    }
}
